In [1]:
import torch
print(torch.__version__)

1.0.0


In [3]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [4]:
tensor_uninit = torch.Tensor(3,3)

In [5]:
torch.numel(tensor_uninit)

9

In [6]:
tensor_uninit

tensor([[0.0000e+00, 0.0000e+00, 5.8854e+14],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [       nan,        nan, 0.0000e+00]])

In [7]:
tensor_init = torch.rand(3,3)
tensor_init

tensor([[0.0297, 0.1517, 0.5667],
        [0.9093, 0.7636, 0.0944],
        [0.1174, 0.5567, 0.6803]])

In [10]:
tensor_int = torch.randn(6,3).type(torch.IntTensor)
tensor_int

tensor([[ 1,  0,  1],
        [-1,  0,  0],
        [ 0,  0,  0],
        [ 1, -1, -1],
        [ 0, -1,  1],
        [ 0,  0,  0]], dtype=torch.int32)

In [11]:
tensor_long = torch.LongTensor([1.0,2.0,3.1,4.1])
tensor_long

tensor([1, 2, 3, 4])

In [12]:
tensor_byte = torch.ByteTensor([0, 261, 1, -5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [13]:
tensor_ones = torch.ones(6)
tensor_ones

tensor([1., 1., 1., 1., 1., 1.])

In [14]:
tensor_zeroes = torch.zeros(6)
tensor_zeroes

tensor([0., 0., 0., 0., 0., 0.])

In [15]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [17]:
ones_shape_eye = torch.ones_like(tensor_eye)
ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
initial_tensor = torch.rand(3,3)
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [21]:
new_tensor = initial_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [23]:
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [24]:
initial_tensor.add_(5)
initial_tensor

tensor([[13., 13., 13.],
        [13., 13., 13.],
        [13., 13., 13.]])

In [25]:
initial_tensor = torch.rand(2,3)

In [26]:
initial_tensor

tensor([[0.4628, 0.8066, 0.3018],
        [0.4168, 0.5414, 0.5979]])

In [27]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)

In [28]:
sorted_tensor

tensor([[0.3018, 0.4628, 0.8066],
        [0.4168, 0.5414, 0.5979]])

In [29]:
sorted_indices

tensor([[2, 0, 1],
        [0, 1, 2]])

In [30]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor, dim=0)

In [31]:
sorted_tensor

tensor([[0.4168, 0.5414, 0.3018],
        [0.4628, 0.8066, 0.5979]])

In [32]:
sorted_indices

tensor([[1, 1, 0],
        [0, 0, 1]])

In [33]:
initial_tensor[0,2]

tensor(0.3018)

In [34]:
initial_tensor[:,1:]

tensor([[0.8066, 0.3018],
        [0.5414, 0.5979]])

In [35]:
initial_tensor.size()

torch.Size([2, 3])

In [37]:
initial_tensor.shape

torch.Size([2, 3])

In [38]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [39]:
resized_tensor

tensor([0.4628, 0.8066, 0.3018, 0.4168, 0.5414, 0.5979])

In [40]:
initial_tensor[0, 2] = 0.1111
resized_tensor

tensor([0.4628, 0.8066, 0.1111, 0.4168, 0.5414, 0.5979])

In [41]:
resized_tensor = initial_tensor.view(3,2)
resized_tensor.shape

torch.Size([3, 2])

In [42]:
resized_tensor

tensor([[0.4628, 0.8066],
        [0.1111, 0.4168],
        [0.5414, 0.5979]])

In [43]:
resized_matrix = initial_tensor.view(2, -1)
resized_matrix.shape

torch.Size([2, 3])

In [44]:
resized_matrix = initial_tensor.view(-1, 5)

RuntimeError: shape '[-1, 5]' is invalid for input of size 6

In [45]:
topk_tensor, topk_indices = torch.topk(initial_tensor, 2)
topk_tensor

tensor([[0.8066, 0.4628],
        [0.5979, 0.5414]])

In [46]:
topk_indices

tensor([[1, 0],
        [2, 1]])

In [47]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [48]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [50]:
float1 = torch.FloatTensor([2])
float2 = torch.FloatTensor([3])
float1 + float2

tensor([5.])

In [51]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))
print(rand1, '\n', rand2)

tensor([[1.7166, 0.5022, 0.2282],
        [0.7943, 1.0747, 0.2302]]) 
 tensor([[0.7967, 0.8706, 0.3743],
        [0.1763, 0.8984, 1.1804]])


In [52]:
add1 = rand1 + rand2
add1

tensor([[2.5133, 1.3728, 0.6025],
        [0.9706, 1.9731, 1.4106]])

In [53]:
rand1.add_(rand2)
rand1

tensor([[2.5133, 1.3728, 0.6025],
        [0.9706, 1.9731, 1.4106]])

In [54]:
add2 = torch.add(rand1, rand2)
add2

tensor([[3.3100, 2.2435, 0.9768],
        [1.1468, 2.8716, 2.5911]])

In [55]:
add_scalar_plus = rand1 + 10
add_scalar_plus

tensor([[12.5133, 11.3728, 10.6025],
        [10.9706, 11.9731, 11.4106]])

In [56]:
add_scalar = torch.add(rand1, 10)
add_scalar

tensor([[12.5133, 11.3728, 10.6025],
        [10.9706, 11.9731, 11.4106]])

In [57]:
tensor = torch.Tensor([[-1, 0.3, 2],
                      [-4, 5, -0.4]])

In [58]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 0.5000, 0.8696],
        [1.0811, 0.9434, 4.0000]])

In [59]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[ 1.0000,  0.0900,  4.0000],
        [16.0000, 25.0000,  0.1600]])

In [60]:
tensor_mul = torch.mul(tensor, 10)
tensor_mul

tensor([[-10.,   3.,  20.],
        [-40.,  50.,  -4.]])

In [65]:
tensor_clamp = torch.clamp(tensor, min=-0.5, max=0.5)
tensor_clamp

tensor([[-0.5000,  0.3000,  0.5000],
        [-0.5000,  0.5000, -0.4000]])

In [66]:
transposed_tensor = tensor.t()
transposed_tensor

tensor([[-1.0000, -4.0000],
        [ 0.3000,  5.0000],
        [ 2.0000, -0.4000]])

In [67]:
t1 = torch.Tensor([4,2])
t2 = torch.Tensor([3,1])

In [68]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(14.)

In [69]:
matrix = torch.Tensor([[2,5,3],
                      [4,1,0]])
vector = torch.Tensor([3,5,0])

In [70]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([31., 17.])

In [71]:
another_matrix = torch.Tensor([[1,3],
                              [2,0],
                              [0,5]])

In [72]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[12., 21.],
        [ 6., 12.]])

In [73]:
import numpy as np

In [74]:
numpy_arr = np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [75]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [76]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [78]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [79]:
tensor

tensor([1, 4, 3], dtype=torch.int32)

In [80]:
numpy_from_tensor

array([1, 4, 3])